site_name: cl-waffe2 Documentation

nav:
    - Home: index.md
    - Tutorial: overview.md
    - cl-waffe2/distributions: distributions.md

theme: readthedocs

markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      