site_name: cl-waffe2 Documentation

nav:
    - Home: index.md
    - Tutorials: overview.md
    - Tips: Tips.md
    - cl-waffe2/vm.nodes: nodes.md
    - cl-waffe2/vm.generic-tensor: generic-tensor.md
    - cl-waffe2/base-impl: base-impl.md
    - cl-waffe2/distributions: distributions.md

theme: readthedocs

markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      