site_name: cl-waffe2 Documentation

nav:
    - Overview: index.md
    - Install: install.md
    - Examples: examples.md
    - Learn More: overview.md
    - cl-waffe2: utils.md
    - cl-waffe2/vm.nodes: nodes.md
    - cl-waffe2/vm.generic-tensor: generic-tensor.md
    - cl-waffe2/vm: vm.md
    - "[Functions] cl-waffe2/base-impl": base-impl.md
    - "[Nodes] cl-waffe2/base-impl": base-impl-nodes.md
    - cl-waffe2/distributions: distributions.md
    - cl-waffe2/nn: nn.md
    - cl-waffe2/optimizers: optimizer.md
    - cl-waffe2/backends.lisp: lisp-tensor-backend.md
    - cl-waffe2/backends.cpu: cpu-tensor-backend.md
    - cl-waffe2/backends.jit.cpu: cpu-jit-tensor-backend.md

theme: readthedocs

markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      